server:
  port: 8888

spring:
  security:
#    user:
#      name: admin
#      password: admin
  datasource:
    url: jdbc:mysql://139.196.112.185:3306/DB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
